export const SET_FILTER_TERM = 'SET_FILTER_TERM'
export const CHANGE_FOUNDED_TASKS = 'CHANGE_FOUNDED_TASKS'
export const TOGGLE_FILTER_TERM = 'TOGGLE_FILTER_TERM'

export const ADD_TASK = 'ADD_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
export const TOGGLE_TASK_STATE = 'TOGGLE_TASK_STATE';

export const SET_FILTER_STATE = 'SET_FILTER_STATE';

